---
- name: Prepare system
  ansible.builtin.include_tasks: prepare.yml

- name: Install NiFi Registry
  ansible.builtin.include_tasks: install.yml

- name: Customize NiFi Registry
  ansible.builtin.include_tasks: customize.yml

- name: Run NiFi Registry as system service
  ansible.builtin.include_tasks: run.yml
